name: multi_thumb_range_slider_example
description: "Example app for the multi_thumb_range_slider package"
publish_to: 'none'

version: 1.1.1+3

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  multi_thumb_range_slider:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
