name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
          
      - name: Run tests
        run: flutter test
          
      - name: Deploy Flutter Web App
        uses: bluefireteam/flutter-gh-pages@v9
        with:
          # WICHTIG: Gibt an, dass alle Flutter-Befehle im 'example'-Verzeichnis ausgeführt werden sollen
          workingDir: example
          # WICHTIG: Setzt die Basis-URL für deine App.
          # Dies ist notwendig, da die Seite unter deinedomain.de/repository-name/ gehostet wird.
          baseHref: /multi_thumb_slider/
          # Das GITHUB_TOKEN wird automatisch von GitHub bereitgestellt und wird benötigt,
          # um in den gh-pages Branch deines Repositories zu pushen.
          token: ${{ secrets.GITHUB_TOKEN }}